---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: rust:latest
  environment:
    CARGO_TARGET_DIR: /var/cache/drone/cargo
    CARGO_HOME: /var/cache/drone/cargo
  commands:
  - apt-get update -qq; apt-get install -y build-essential curl xz-utils clang llvm
  - cargo build
  - cargo test
  - cargo test --release

