---
kind: pipeline
type: docker
name: default

workspace:
  path: /submodules/tensorflow

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --recursive --remote

- name: build_tensorflow
  image: gcc
  commands:
  - make -f tensorflow/lite/micro/tools/make/Makefile test_magic_wand_test 

- name: build
  image: rust:latest
  environment:
    CARGO_TARGET_DIR: /var/cache/drone/cargo
    CARGO_HOME: /var/cache/drone/cargo
  commands:
  - apt-get update -qq; apt-get install -y build-essential curl xz-utils clang llvm
  - cargo build
  - cargo test
  - cargo test --release

