---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: rust:latest
  environment:
    CARGO_TARGET_DIR: /var/cache/drone/cargo
    CARGO_HOME: /var/cache/drone/cargo
  commands:
  - yes | apt install llvm clang
  - cargo build
  - cargo test
  - cargo test --release

