name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.1.1

     
    - name: Build
      uses: actions/checkout@v2
    - run: |
        cargo build --verbose --all-targets
        cargo build --release --verbose --all-targets
    - name: Run tests
      run: |
        cargo test --verbose
        cargo test --verbose --release
        
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.TOKEN }}
          args: --all-features
