name: Rust

on: [push, pull_request]

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: textbook/git-checkout-submodule-action@2.1.1
      - uses: docker://gcc
      - name: Build tensorflow
        run: |
          sudo apt-get update -qq >/dev/null 2>&1 && sudo apt-get install -yqq xxd
          cd submodules/tensorflow
          sudo make -f tensorflow/lite/micro/tools/make/Makefile test_magic_wand_test 
          sudo chmod a+rwx -R .
      - uses: actions-rs/toolchain@master
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Build
        run: |
          cargo build --verbose --all-targets --features=no-c-warnings
          cargo test --verbose  --all-targets --features=no-c-warnings
          
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: textbook/git-checkout-submodule-action@2.1.1
      - uses: docker://gcc
      - name: Build tensorflow
        run: |
          sudo apt-get update -qq >/dev/null 2>&1 && sudo apt-get install -yqq xxd
          cd submodules/tensorflow
          sudo make -f tensorflow/lite/micro/tools/make/Makefile test_magic_wand_test
          sudo chmod a+rwx -R . 
      - uses: actions-rs/toolchain@master
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Build
        run: |
          cargo build --release --verbose --all-targets --features=no-c-warnings
          cargo test --release --verbose  --all-targets --features=no-c-warnings
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: textbook/git-checkout-submodule-action@2.1.1
      - uses: docker://gcc
      - name: Build tensorflow
        run: |
          sudo apt-get update -qq >/dev/null 2>&1 && sudo apt-get install -yqq xxd
          cd submodules/tensorflow
          sudo make -f tensorflow/lite/micro/tools/make/Makefile test_magic_wand_test 
          sudo chmod a+rwx -R .
      - uses: actions-rs/toolchain@master
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Build
        run: |
          cargo clippy --features=no-c-warnings --all-targets
          
